apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-redis
  namespace: default
  labels:
    app: airflow-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-redis
  template:
    metadata:
      labels:
        app: airflow-redis
    spec:
      hostname: airflow-redis
      containers:
      - name: airflow-redis
        image: redis:7.2-bookworm
        resources:
          requests:
            memory: "2024Mi"
            cpu: "250m"
          limits:
            memory: "2024Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-redis
  namespace: default 
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: airflow-redis
