apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
  namespace: default
  labels:
    app: airflow-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airflow-worker
  template:
    metadata:
      labels:
        app: airflow-worker
    spec:
      initContainers:
      - name: init-wait-1
        image: alpine:3.22.2
        command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 airflow-apiserver 8086 && exit 0 || sleep 3; done; exit 1"]
      volumes:
      - name: host-folder-storage-airflow-dags
        hostPath:
          path: /home/stanislav/k8s/25_11/airflow/dags
          type: Directory
      containers:
      - name: airflow-worker
        image: stanislavko2/bigdata25_airflow:3.1.3
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2024Mi"
            cpu: "350m"
          limits:
            memory: "2024Mi"
            cpu: "500m"
        volumeMounts:
        - name: host-folder-storage-airflow-dags
          mountPath: /opt/airflow/dags
#        ports:
#        - containerPort: 8974
        securityContext:
          runAsUser: 50000
        command:
        - /bin/bash
        - -c
        - airflow celery worker
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: "CeleryExecutor"
#        - name: AIRFLOW__CORE__AUTH_MANAGER
#          value: "airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager"
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow"
        - name: AIRFLOW__CELERY__RESULT_BACKEND
          value: "db+postgresql://airflow:airflow@airflow-postgres/airflow"
        - name: AIRFLOW__CELERY__BROKER_URL
          value: "redis://:@airflow-redis:6379/0"
        - name: AIRFLOW__CORE__FERNET_KEY
          value: ""
        - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
          value: "true"
        - name: AIRFLOW__CORE__LOAD_EXAMPLES
          value: "false"
        - name: AIRFLOW__CORE__EXECUTION_API_SERVER_URL
          value: "http://airflow-apiserver:8086/execution/"
        - name: AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK
          value: "true"
        - name: AIRFLOW__API_AUTH__JWT_SECRET
          value: "cXdlcnR5"
#        - name: AIRFLOW_CONFIG
#          value: "/opt/airflow/config/airflow.cfg"

