apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-3
  namespace: default
  labels:
    app: kafka-broker-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-3
  template:
    metadata:
      labels:
        app: kafka-broker-3
    spec:
      hostname: kafka-broker-3
      initContainers:
      - name: init-wait
        image: alpine:3.22.2
        command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 zookeeper-1 2181 && exit 0 || sleep 3; done; exit 1"]
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.3.2
        resources:
          requests:
            memory: "4024Mi"
            cpu: "250m"
          limits:
            memory: "4024Mi"
            cpu: "500m"
        ports:
        - containerPort: 9094
        - containerPort: 29094
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-1:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "PLAINTEXT"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-broker-3:29094,PLAINTEXT_HOST://kafka-broker-3:9094"
        - name: KAFKA_BROKER_ID
          value: "3"
        - name: KAFKA_HEAP_OPTS
          value: "-Xms3772m -Xmx3772m"
        - name: KAFKA_LOG_RETENTION_BYTES
          value: "1000000"
        - name: LOG_RETENTION_BYTES
          value: "1000000"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-3
  namespace: default
spec:
  ports:
  - name: external
    port: 9094
    targetPort: 9094
  - name: internal
    port: 29094
    targetPort: 29094
  selector:
    app: kafka-broker-3
  type: ClusterIP
