apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-monitoring-ui
  namespace: default
  labels:
    app: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      initContainers:
      - name: init-wait-1
        image: alpine:3.22.2
        command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 kafka-broker-1 9092 && exit 0 || sleep 3; done; exit 1"]
      - name: init-wait-2
        image: alpine:3.22.2
        command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 kafka-broker-2 9093 && exit 0 || sleep 3; done; exit 1"]
      - name: init-wait-3
        image: alpine:3.22.2
        command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 kafka-broker-3 9094 && exit 0 || sleep 3; done; exit 1"]
      containers:
      - name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        resources:
          requests:
            memory: "2024Mi"
            cpu: "250m"
          limits:
            memory: "2124Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_CLUSTERS_0_NAME
          value: "local"
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: "kafka-broker-1:9092,kafka-broker-2:9093,kafka-broker-3:9094"
        - name: KAFKA_CLUSTERS_0_ZOOKEEPER
          value: "zookeeper-1:2181"
        - name: AUTH_TYPE
          value: "LOGIN_FORM"
        - name: SPRING_SECURITY_USER_NAME
          value: "stanislav"
        - name: SPRING_SECURITY_USER_PASSWORD
          value: "qwerty"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: default
spec:
  ports:
  - port: 8082
    targetPort: 8080
  selector:
    app: kafka-ui
  type: LoadBalancer
