#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: connector-pv-volume
#  labels:
#    type: local
#    purpose: connector-storage
#spec:
#  storageClassName: manual
#  capacity:
#    storage: 1Mi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/home/stanislav/k8s/25_11/kafka_connect/connect-jars"
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: connector-pv-claim
#spec:
#  storageClassName: manual
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Mi
#  selector:
#    matchLabels:
#      purpose: connector-storage
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect-ws-1
  namespace: default
  labels:
    app: kafka-connect-ws-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect-ws-1
  template:
    metadata:
      labels:
        app: kafka-connect-ws-1
    spec:
      hostname: kafka-connect-ws-1
      initContainers:
      - name: init-wait
        image: alpine:3.22.2
        command: ["sh", "-c", "for i in $(seq 1 300); do nc -zvw1 schema-registry-1 8081 && exit 0 || sleep 3; done; exit 1"]
 #     volumes:
 #       - name: connector-pv-storage
 #         persistentVolumeClaim:
 #           claimName: connector-pv-claim
      volumes:
      - name: host-folder-storage
        hostPath:
          path: /home/stanislav/k8s/25_11/kafka_connect
          type: Directory
      containers:
      - name: kafka-connect
        image: confluentinc/cp-kafka-connect:7.3.2
        resources:
          requests:
            memory: "2024Mi"
            cpu: "250m"
          limits:
            memory: "2024Mi"
            cpu: "500m"
        volumeMounts:
        - name: host-folder-storage
          mountPath: /data
        ports:
        - containerPort: 8083
        - containerPort: 28083
#        volumeMounts:
#          - mountPath: "/data"
#            name: connector-pv-storage
        command: ["/bin/bash", "-c", "/data/connect-ws-jars/start.sh"]
        env:
        - name: KAFKA_HEAP_OPTS
          value: "-Xms1772m -Xmx1772m"
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: "kafka-broker-1:9092,kafka-broker-2:9093,kafka-broker-3:9094"
        - name: CONNECT_REST_PORT
          value: "8083"
        - name: CONNECT_GROUP_ID
          value: "CONNECT_GROUP_ID"
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: "_connect-configs"
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: "_connect-offsets"
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: "_connect-status"
        - name: CONNECT_KEY_CONVERTER
          value: "org.apache.kafka.connect.storage.StringConverter"
        - name: CONNECT_VALUE_CONVERTER
          value: "org.apache.kafka.connect.storage.StringConverter"
        - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
          value: "http://schema-registry-1:8081"
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          value: "kafka-connect-ws-1"
        - name: CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN
          value: "[%d] %p %X{connector.context}%m (%c:%L)%n"
        - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_LOG4J_ROOT_LOGLEVEL
          value: "INFO"
        - name: CONNECT_PLUGIN_PATH
          value: "/usr/share/java,/usr/share/confluent-hub-components,/data/connect-ws-jars"
#      volumes:
#        - /home/stanislav/k8s/25_11/kafka_connect:/data
---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: my-server
#spec:
#  containers:
#  - name: my-server
#    image: alpine
##    volumeMounts:
##    - mountPath: /data
##      name: connector-pv-storage
#    volumeMounts:
#    - mountPath: /data
#      name: volume
#    # Just spin & wait forever
#    command: [ "/bin/sh", "-c", "--" ]
#    args: [ "while true; echo 'asdf'; ls /data; ls /data/connect-ws-jars; do sleep 10; done;" ]
##  volumes:
##    - name: connector-pv-storage
##      persistentVolumeClaim:
##        claimName: connector-pv-claim
#  volumes:
#  - name: volume
#    hostPath:
#      path: /home/stanislav/k8s/25_11/kafka_connect_pod
#      type: Directory
#---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-ws-1
  namespace: default
spec:
  ports:
  - name: external
    port: 8083
    targetPort: 8083
  - name: internal
    port: 28083
    targetPort: 28083
  selector:
    app: kafka-connect-ws-1
  type: ClusterIP
