apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: default
  labels:
    app: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      hostname: spark-master
      volumes:
      - name: host-folder-storage-spark
        hostPath:
          path: /home/stanislav/k8s/25_11/spark
          type: Directory
      containers:
      - name: spark-master
        image: stanislavko2/bigdata25_spark:3.5.7
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2024Mi"
            cpu: "251m"
          limits:
            memory: "2024Mi"
            cpu: "500m"
        volumeMounts:
        - name: host-folder-storage-spark
          mountPath: /opt/spark/my_jars
        - name: host-folder-storage-spark
          mountPath: /opt/spark/jars/spark-iceberg-1.0.0.jar
          subPath: spark-iceberg-1.0.0.jar
        ports:
        - containerPort: 7077
        - containerPort: 8080
        - containerPort: 4040
        - containerPort: 6066
        command:
        - /bin/bash
        - -c
        - >
          /opt/spark/sbin/start-master.sh && tail -f /dev/null
        env:
        - name: SPARK_MASTER_HOST
          value: "spark-master"
        - name: SPARK_MASTER_PORT
          value: "7077"
        - name: DELME
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: default 
spec:
  ports:
  - name: rest
    port: 8087
    targetPort: 8080
  - name: submit
    port: 6066
    targetPort: 6066
  - name: master
    port: 7077
    targetPort: 7077
  - name: aux
    port: 4040
    targetPort: 4040
  selector:
    app: spark-master
