apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-ui
  namespace: default
  labels:
    app: zookeeper-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-ui
  template:
    metadata:
      labels:
        app: zookeeper-ui
    spec:
      initContainers:
      - name: init-wait
        image: alpine:3.22.2
        command: ["sh", "-c", "for  i in $(seq 1 300); do nc -zvw1 zookeeper-1 2181 && exit 0 || sleep 3; done; exit 1"]
      containers:
      - name: zookeeper-ui
        image: elkozmon/zoonavigator:1.1.3
        resources:
          requests:
            memory: "1024Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
        env:
        - name: ZK_CLIENT_CONNECTION_STRING
          value: "zookeeper-1:2181"
        - name: HTTP_PORT
          value: "9000"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-ui
  namespace: default 
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: zookeeper-ui
